from tkinter.ttk import Combobox
from tkinter import messagebox
from tkinter import*
from tkinter import PhotoImage
from PIL import ImageTk
from twilio.rest import Client
import random
import pymysql as m
tab=Tk()
tab.title("BookMyShow")
tab.geometry("2000x2000")
tab.configure(bg="#9EDDFF")

def Jailer():
    tb=Tk()
    tb.title("BookShow")
    tb.geometry("500x500")
    tb.configure(bg="#A6F6FF")
    th=Label(tb,text="Theatre:",font=("Times New Roman",18,"bold"),bg="#6499E9")
    th.place(x=20,y=60)
    Combo=Combobox(tb)
    Combo['values']=("--SelectTheatre","INOX","ARRS MULTIPLX","SREE RAJASABARI","KAILASH PRAKASH")
    Combo.place(x=150,y=100)
    th=Label(tb,text="Language:",font=("Times New Roman",18,"bold"),bg="#6499E9")
    th.place(x=20,y=150)
    Combo1=Combobox(tb)
    Combo1['values']=("--SelectLanguage","TAMIL","TELEGU","HINDI")
    Combo1.place(x=150,y=200)
    th=Label(tb,text="Format:",font=("Times New Roman",18,"bold"),bg="#6499E9")
    th.place(x=20,y=250)
    Combo2=Combobox(tb)
    Combo2['values']=("--SelectFormat","2D","3D",)
    Combo2.place(x=150,y=300)
    def  save():
        A=Combo.get()
        B=Combo1.get()
        C=Combo2.get()
        if A=="" or B==""or C=="":
            messagebox.showerror("error","fill the details")
        else:
            db=m.connect(host="localhost",user="root",password="1234",db="book")
            cur=db.cursor()
            cur.execute("insert into show values('"+A+"','"+B+"','"+C+"')")
            db.commit()
    bo=Button(tb,text="save",font=("Times New Roman",22,"bold"),bg="#5B0888",fg="black",activebackground="red",activeforeground="red",command=save)
    bo.place(x=150,y=430 )
    bo=Button(tb,text="BookJailers",font=("Times New Roman",22,"bold"),bg="#5B0888",fg="black",activebackground="red",activeforeground="red",command=snacks)
    bo.place(x=150,y=330)


def Vikram():
    ta=Toplevel()
    ta.title("BookShow")
    ta.geometry("500x500")
    ta.configure(bg="#A6F6FF")
    thh=Label(ta,text="Theatre:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    thh.place(x=20,y=60)
    Combo=Combobox(ta)
    Combo['values']=("--SelectTheatre","INOX","ARRS MULTIPLX","SREE RAJASABARI","KAILASH PRAKASH")
    Combo.place(x=150,y=100)
    thh=Label(ta,text="Language:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    thh.place(x=20,y=150)
    Combo1=Combobox(ta)
    Combo1['values']=("--SelectLanguage","TAMIL","TELEGU","HINDI")
    Combo1.place(x=150,y=200)
    thh=Label(ta,text="Format:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    thh.place(x=20,y=250)
    Combo2=Combobox(ta)
    Combo2['values']=("--SelectFormat","2D","3D",)
    Combo2.place(x=150,y=300)
    
    boo=Button(ta,text="BookVikram",font=("Times New Roman",22,"bold"),bg="#5B0888",fg="black",activebackground="red",activeforeground="red",command=snacks)
    boo.place(x=150,y=350)
def Avengers():
    tabs=Toplevel()
    tabs.title("BookShow")
    tabs.geometry("500x500")
    tabs.configure(bg="#A6F6FF")
    po=Label(tabs,text="Theatre:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    po.place(x=20,y=60)
    Combo=Combobox(tabs)
    Combo['values']=("--SelectTheatre","INOX","ARRS MULTIPLX","SREE RAJASABARI","KAILASH PRAKASH")
    Combo.place(x=150,y=100)
    po=Label(tabs,text="Language:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    po.place(x=20,y=150)
    Combo1=Combobox(tabs)
    Combo1['values']=("--SelectLanguage","TAMIL","TELEGU","HINDI")
    Combo1.place(x=150,y=200)
    po=Label(tabs,text="Format:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    po.place(x=20,y=250)
    Combo2=Combobox(tabs)
    Combo2['values']=("--SelectFormat","2D","3D",)
    Combo2.place(x=150,y=300)
   
    z=Button(tabs,text="BookAvengers",font=("Times New Roman",22,"bold"),bg="#5B0888",fg="black",activebackground="red",activeforeground="red",command=snacks)
    z.place(x=150,y=350)
def Shershaah():
    zx=Toplevel()
    zx.title("BookShow")
    zx.geometry("500x500")
    zx.configure(bg="#A6F6FF")
    xc=Label(zx,text="Theatre:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    xc.place(x=20,y=60)
    Combo=Combobox(zx)
    Combo['values']=("--SelectTheatre","INOX","ARRS MULTIPLX","SREE RAJASABARI","KAILASH PRAKASH")
    Combo.place(x=150,y=100)
    xc=Label(zx,text="Language:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    xc.place(x=20,y=150)
    Combo1=Combobox(zx)
    Combo1['values']=("--SelectLanguage","TAMIL","TELEGU","HINDI")
    Combo1.place(x=150,y=200)
    xc=Label(zx,text="Format:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    xc.place(x=20,y=250)
    Combo2=Combobox(zx)
    Combo2['values']=("--SelectFormat","2D","3D",)
    Combo2.place(x=150,y=300)
    x=Button(zx,text="BookShershaah",font=("Times New Roman",22,"bold"),bg="#5B0888",fg="black",activebackground="red",activeforeground="red",command=snacks)
    x.place(x=150,y=350)
def SitaRamam():
    cv=Toplevel()
    cv.title("BookShow")
    cv.geometry("500x500")
    cv.configure(bg="#A6F6FF")
    cz=Label(cv,text="Theatre:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    cz.place(x=20,y=60)
    Combo=Combobox(cv)
    Combo['values']=("--SelectTheatre","INOX","ARRS MULTIPLX","SREE RAJASABARI","KAILASH PRAKASH")
    Combo.place(x=150,y=100)
    cz=Label(cv,text="Language:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    cz.place(x=20,y=150)
    Combo1=Combobox(cv)
    Combo1['values']=("--SelectLanguage","TAMIL\nRs.120","TELEGU\nRs.150","HINDI\nRs.170")
    Combo1.place(x=150,y=200)
    cz=Label(cv,text="Format:",font=("Times New Roman",18,"bold"),bg="#5CD2E6")
    cz.place(x=20,y=250)
    Combo2=Combobox(cv)
    Combo2['values']=("--SelectFormat","2D","3D",)
    Combo2.place(x=150,y=300)
    
    m=Button(cv,text="BookSitaRamam",font=("Times New Roman",22,"bold"),bg="#5B0888",fg="black",activebackground="red",activeforeground="red",command=snacks)
    m.place(x=150,y=350)
def snacks():
    sn=Toplevel()
    sn.title("Snacks")
    sn.geometry("700x700")
    sn.configure(bg="#9EDDFF")
    la=Label(sn,text="SnacksMenu",font=("ariel",20),bg="blue")
    la.place(x=50,y=50)
    ck=IntVar()
    ckbt1=Checkbutton(sn,text="Popcorn Rs-40",variable=ck,onvalue=1,offvalue=0,height=3,width=10,bg="#9EDDFF")
    ckbt1.place(x=50,y=100)
    ckbt2=Checkbutton(sn,text="Coke Rs-20",variable=ck,onvalue=2,offvalue=0,height=3,width=10,bg="#9EDDFF")
    ckbt2.place(x=50,y=200)
    up=Button(sn,text="BookNow",font=("Times New Roman",22,"bold"),bg="#9EDDFF",fg="black",activebackground="red",activeforeground="red",command=BookNow)
    up.place(x=150,y=350)
    pp=Button(sn,text="OTP Verify",font=("Times New Roman",22,"bold"),bg="#9EDDFF",fg="black",activebackground="red",activeforeground="red",command=pay)
    pp.place(x=150,y=450)
    ya=Label(sn,text="No.Of.Persons",font=("Times New Roman",20),bg="#9EDDFF")
    ya.place(x=50,y=250)
    ta=Label(sn,text="Per Person Rs-120",font=("Times New Roman",15),bg="#9EDDFF")
    ta.place(x=50,y=290)
    sp=Spinbox(sn,from_=1,to=10)
    sp.place(x=230,y=250)
def pay():
    yu=Toplevel()
    yu.title("Payment")
    yu.geometry("500x500")
    yu.configure(bg="#0E21A0")
    TWILIO_ACCOUNT_SID = "To twilio account no"
    TWILIO_AUTH_TOKEN = "Twilio auth token"
    TWILIO_PHONE_NUMBER = "Twilio Phone Number"
    client=Client(TWILIO_ACCOUNT_SID,TWILIO_AUTH_TOKEN)
    otp=str(random.randint(1000, 9999))
    to_phone_number ="Your Phone Number"
    from_phone_number = '+13348010675'
    message_body = f' Your OTP is:  {otp}'
    message = client.messages.create (
        body=message_body,
        from_=from_phone_number,
        to=to_phone_number)
    r=Label(yu,text="Enter OTP",font=("Times New Roman",15),fg="blue",bg="#A6F6FF")
    r.place(x=30,y=70)
    r=Entry(yu,width=20)
    r.place(x=130,y=70)
    def verify():
        N=r.get()
        if (N==otp):
            x=Label(yu,text="OTP is verified",font=("ariel",15),bg="#82A0D8")
            x.place(x=150,y=120)
        else:
            d=Label(yu,text="OTP not verified",font=("ariel",20),bg="#82A0D8")
            d.place(x=150,y=160)
    op=Button(yu,text="BookPage",font=("Times New Roman",22,"bold"),bg="#9EDDFF",fg="black",activebackground="red",activeforeground="red",command=BookNow)
    op.place(x=150,y=300)
    op=Button(yu,text="Verify",font=("Times New Roman",22,"bold"),bg="#9EDDFF",fg="black",activebackground="red",activeforeground="red",command=verify)
    op.place(x=150,y=400)


        

def BookNow():
    import webbrowser
    webbrowser.open("https://buy.stripe.com/test_bIY7tI4gbcG4fTi8ww")
    
   # er=Label(nn,text="Your Booking is Conform",font=("ariel",20),bg="green")
    #er.pack()

l=Label(tab,text="BookMyShow",font=("ariel",30),bg="red")
l.pack()
jailer=PhotoImage(file="jailers.png")
jai=Label(tab,image=jailer)
jai.place(x=60,y=150)
h=Label(tab,text="Recommended Movies:",font=("Times New Roman",20,"bold"),fg="black")
h.place(x=40,y=100)
vikrams=PhotoImage(file="vikram.png")
vik=Label(tab,image=vikrams)
vik.place(x=300,y=150)
end=PhotoImage(file="endgame.png")
game=Label(tab,image=end)
game.place(x=520,y=147)
sh=PhotoImage(file="shershaah.png")
er=Label(tab,image=sh)
er.place(x=740,y=150)
si=PhotoImage(file="sitaramam.png")
ra=Label(tab,image=si)
ra.place(x=980,y=150)
i=Label(tab,text="ICC Events",font=("Times New Roman",25),bg="blue")
i.place(x=40,y=600)
ic=PhotoImage(file="icc.png")
cr=Label(tab,image=ic)
cr.place(x=300,y=630)
o=PhotoImage(file="book.png")
ok=Label(tab,image=o)
ok.place(x=450,y=0)
b=Button(tab,text="BookJailer",font=("Times New Roman",15,"bold"),bg="red",fg="black",activebackground="red",activeforeground="red",command=Jailer)
b.place(x=80,y=450)
v=Button(tab,text="BookVikram",font=("Times New Roman",15,"bold"),bg="red",fg="black",activebackground="red",activeforeground="red",command=Vikram)
v.place(x=320,y=450)
a=Button(tab,text="Book Avengers",font=("Times New Roman",15,"bold"),bg="red",fg="black",activebackground="red",activeforeground="red",command=Avengers)
a.place(x=520,y=450)
s=Button(tab,text="BookShershaah",font=("Times New Roman",15,"bold"),bg="red",fg="black",activebackground="red",activeforeground="red",command=Shershaah)
s.place(x=750,y=450)
ma=Button(tab,text="BookSitaRamam",font=("Times New Roman",15,"bold"),bg="red",fg="black",activebackground="red",activeforeground="red",command=SitaRamam)
ma.place(x=990,y=450)
icc=Button(tab,text="BookMatches",font=("Times New Roman",22,"bold"),bg="#AED2FF",fg="black",activebackground="red",activeforeground="red",command="BookMatches")
icc.place(x=1300,y=650)



